### ISSUE TITLE
open session not working

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#9]
Nothing happens when a saved session is opened.

**Comment by 3fon3fonov** [comment]
Hi Mathias, that cannot be. Keep in mind that you can save/open "sessions", which have only one fit inside, or "multy-sessions" which can have more than one fit. If you saved a multi-session you must load it as such.

**Comment by 3fon3fonov** [comment]
Did you manage sorting this out? Let us know if you figured out how to open/save sessions, or you still have problems.

**Comment by mzechmeister** [comment]
Still nothings happens when loading a session, even when saving only one fit as a session.
But multisession works!

Session and Multisession is confusing. Merge them.

**Comment by 3fon3fonov** [comment]
> Still nothings happens when loading a session, even when saving only one fit as a session.

Mathias, sorry for the confusion. When you add a "session" then it is added below the previous.... and if your first one is empty, you keep seeing default one. Go to the session combo-box and you will see that the session was actually imported. You just have to select it. I bet this was the problem.


> Session and Multisession is confusing. Merge them.

The session/multi-session is a legacy code from which I wanted to get rid at some point. I fully agree to merge these two into one option. Will do it soon.

**Comment by 3fon3fonov** [comment]
The session window behavior is now fixed.  When you add a session it will be auto-loaded and it will appear at the bottom of the session list. Same for the multi-session.  I have a reason to keep the multi-session for now, but later as I said, sessions and multi-sessions will be merged into one session manager.

**Comment by mzechmeister** [comment]
Still not working as expected.
(1) I started the program
(2) I imported 5 RV files.
(3) I saved the session.
(4) I closed and restarted the program.
(3) I loaded the session, but only some statistic is loaded while the **RV files are not shown**.

**Comment by 3fon3fonov** [comment]
there must be an error in the stderr/stdout tab. Copy paste the text here and I will see why.

**Comment by mzechmeister** [comment]
Hm, now it is working, so no stderr/stdout output.
No idea what happened before.

BTW, it would be good to show the session name in the window title.
